name: .NET Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

env:
  DOTNET_VERSION: '8.0.x'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal --logger "trx;LogFileName=test-results.trx"
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.os }}
        path: '**/test-results.trx'
        retention-days: 7

  code-coverage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Debug
    
    - name: Test with coverage
      run: dotnet test --no-build --configuration Debug --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: '**/coverage.opencover.xml'
        flags: unittests
        fail_ci_if_error: false

  publish-nuget:
    needs: [build, code-coverage]
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release
    
    - name: Pack DotEnvX.Core
      run: dotnet pack DotEnvX.Core/DotEnvX.Core.csproj --configuration Release --no-build --output nupkg
    
    - name: Pack DotEnvX.Extensions.DependencyInjection
      run: dotnet pack DotEnvX.Extensions.DependencyInjection/DotEnvX.Extensions.DependencyInjection.csproj --configuration Release --no-build --output nupkg
    
    - name: Pack DotEnvX.Tool
      run: dotnet pack DotEnvX.Tool/DotEnvX.Tool.csproj --configuration Release --no-build --output nupkg
    
    - name: Push to NuGet
      run: dotnet nuget push nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      
  publish-cli-tool:
    needs: [build, code-coverage]
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build CLI Tool
      run: dotnet build DotEnvX.Tool/DotEnvX.Tool.csproj --configuration Release
    
    - name: Pack CLI Tool
      run: dotnet pack DotEnvX.Tool/DotEnvX.Tool.csproj --configuration Release --no-build --output nupkg
    
    - name: Push CLI Tool to NuGet
      run: dotnet nuget push nupkg/DotEnvX.Tool.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate